services:
  server:
    build:
      context: .
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3003
      MYSQL_HOST: db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: chilpost
      MYSQL_PORT: 3306
    ports:
      - 3003:3003
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_DATABASE=chilpost
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 4406:3306
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: database/password.txt
